// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTask(arg1) {
  return window['go']['main']['TaskManager']['AddTask'](arg1);
}

export function GetTasks() {
  return window['go']['main']['TaskManager']['GetTasks']();
}

export function RemoveTask(arg1) {
  return window['go']['main']['TaskManager']['RemoveTask'](arg1);
}

export function ToggleTaskStatus(arg1) {
  return window['go']['main']['TaskManager']['ToggleTaskStatus'](arg1);
}
